# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - hand_controller

  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint0
      - joint1
      - joint2
      - joint3
  hand_controller:
    type: GripperCommand
    joints:
      - joint4_0
      - joint4_1
    action_ns: gripper_cmd
    default: true