controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint0
      - joint1
      - joint2
      - joint3
  - name: fake_Grippers_controller
    type: $(arg fake_execution_type)
    joints:
      - joint4_0
      - joint4_1
initial:  # Define initial robot poses per group
  - group: arm
    pose: home